import type {ToolView} from './WorkspaceChrome';
import {SubmissionWorkspace} from './SubmissionWorkspace';
import {VaultWorkspace} from './VaultWorkspace';
import {AuditWorkspace} from './AuditWorkspace';
import {AnalysisDashboard,type AnalysisCatalog as Catalog,type SavedAnalysis as Analysis,type VersionSelection} from './AnalysisDashboard';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,BarChart3,Download,FileText,AlertCircle,ClipboardCheck} from 'lucide-react';
type Report={id:string;title:string;created:number;series:string;version:number;previous_id:string|null;entity:string;family:string;can_submit?:boolean;audit_status?:string|null;source_family?:string;source_version?:number;source_cadence?:string;source_period?:string};
const reportCategories=[
 ['production_offtake','Production and off-take report'],['financial','Financial report'],
 ['washery_operations','Washery operational report'],['environmental_compliance','Environmental clearance and compliance report'],
 ['operational_statistics','Operational statistic report'],
] as const;
const categoryName=(family:string)=>reportCategories.find(([id])=>id===family)?.[1]||family.replaceAll('_',' ');
async function call<T>(token:string,path:string,method='GET',body?:unknown):Promise<T>{
 const r=await fetch('/api/analytics'+path,{method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'The request could not be completed.');return d;
}
const message=(e:unknown)=>e instanceof Error?e.message:'Request failed.';
export function AnalyticsWorkspace({token,entityCode,technical,view,reviewPosition='contributor'}:{token:string;entityCode:string;technical:boolean;view:ToolView;reviewPosition?:string}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[analyses,setAnalyses]=useState<Analysis[]>([]),[reports,setReports]=useState<Report[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[generating,setGenerating]=useState(false),[quickReport,setQuickReport]=useState<Report|null>(null),[status,setStatus]=useState<{online:boolean;model_ready?:boolean;models:unknown[];message?:string}|null>(null);
 const [entities,setEntities]=useState<string[]>(technical?['ECL','BCCL','CCL','NCL','WCL','SECL','MCL']:[entityCode]),[family,setFamily]=useState('all'),[selected,setSelected]=useState<Record<string,string>>({}),[title,setTitle]=useState(technical?'CMPDI consolidated analysis':entityCode+' report analysis'),[period,setPeriod]=useState(''),[target,setTarget]=useState(technical?'CMPDI':entityCode),[targetFamily,setTargetFamily]=useState(technical?'annual':'production_offtake');
 const [active,setActive]=useState<Analysis|null>(null),[workbench,setWorkbench]=useState(''),[analysesLoaded,setAnalysesLoaded]=useState(false);const frame=useRef<HTMLIFrameElement>(null),restored=useRef(false),recovering=useRef(false);const [includeHistory,setIncludeHistory]=useState(true);
 const activeSessionKey=`cil.analytics.active.${technical?'technical':entityCode}`;
 const [auditPicker,setAuditPicker]=useState(false),[auditTarget,setAuditTarget]=useState<Report|null>(null),[auditCategory,setAuditCategory]=useState('production_offtake'),[auditNotice,setAuditNotice]=useState('');const auditDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(auditPicker)auditDialog.current?.showModal();else if(auditDialog.current?.open)auditDialog.current.close()},[auditPicker]);
 useEffect(()=>{const saved=(event:MessageEvent)=>{if(event.origin===window.location.origin&&event.source===frame.current?.contentWindow&&event.data?.type==='cil-report-saved')void refresh()};window.addEventListener('message',saved);return()=>window.removeEventListener('message',saved)},[token]);
 async function refresh(){setError('');try{const [c,a,r,s]=await Promise.all([call<Catalog>(token,'/catalog?include_history='+includeHistory),call<Analysis[]>(token,'/analyses'),call<Report[]>(token,'/reports'),call<{online:boolean;model_ready?:boolean;models:unknown[];message?:string}>(token,'/status')]);setCatalog(c);setAnalyses(a);setReports(r);setStatus(s);setAnalysesLoaded(true);}catch(e){setError(message(e));}}
 useEffect(()=>{void refresh();},[token,includeHistory]);
 useEffect(()=>{if(!active||active.status!=='importing')return;let done=false;const interval=setInterval(()=>{call<Analysis>(token,'/analyses/'+active.id).then(a=>{if(!done){setActive(a);if(a.status!=='importing'){void refresh();if(a.status==='ready')void open(a);}}}).catch(e=>{if(!done)setError(message(e));});},2500);return()=>{done=true;clearInterval(interval);};},[active?.id,active?.status,token]);
 async function create(version?:VersionSelection){setBusy(true);setError('');try{const versionInputs=version?(catalog?.files||[]).filter(file=>file.supported&&file.family===version.family&&file.version===version.version&&(!version.cadence||file.cadence===version.cadence)&&(!version.period||file.period===version.period)).map(file=>({file_id:file.id,sheet:null})):[];const a=await call<Analysis>(token,'/analyses','POST',{title,period:version?.period||period,scope_entities:entities,target_entity:target,target_family:targetFamily,inputs:versionInputs.length?versionInputs:Object.entries(selected).map(([file_id,sheet])=>({file_id,sheet:sheet||null}))});setActive(a);setWorkbench('');await refresh();if(a.status==='ready')await open(a);}catch(e){setError(message(e));}finally{setBusy(false);}}
 async function generate(version?:VersionSelection,sourceAnalysis?:Analysis){setGenerating(true);setError('');setAuditNotice('');try{const versionInputs=version?(catalog?.files||[]).filter(file=>file.supported&&file.family===version.family&&file.version===version.version&&(!version.cadence||file.cadence===version.cadence)&&(!version.period||file.period===version.period)).map(file=>({file_id:file.id,sheet:null})):[];const selectedInputs=Object.entries(selected).map(([file_id,sheet])=>({file_id,sheet:sheet||null}));const analysisInputs=(sourceAnalysis?.sources||[]).filter(file=>file.supported).map(file=>({file_id:file.id,sheet:null}));const payload:{title:string;period:string;scope_entities:string[];target_entity:string;target_family:string;inputs:{file_id:string;sheet:string|null}[];send_for_audit:boolean;source_family?:string;source_cadence?:string;source_period?:string;source_version?:number}={title:sourceAnalysis?.title||title,period:sourceAnalysis?.period||period,scope_entities:sourceAnalysis?.scope_entities||entities,target_entity:sourceAnalysis?.target_entity||target,target_family:sourceAnalysis?.target_family||(technical&&version?version.family:targetFamily),inputs:versionInputs.length?versionInputs:selectedInputs.length?selectedInputs:analysisInputs,send_for_audit:false};if(version){payload.source_family=version.family;payload.source_cadence=version.cadence;payload.source_period=version.period;payload.source_version=version.version;payload.period=version.period||period;}const report=await call<Report>(token,'/reports/generate','POST',payload);setQuickReport(report);await refresh()}catch(e){setError(message(e))}finally{setGenerating(false)}}
 useEffect(()=>{const requested=(event:MessageEvent)=>{if(event.origin===window.location.origin&&event.source===frame.current?.contentWindow&&event.data?.type==='cil-generate-report'&&!generating&&active)void generate(undefined,active)};window.addEventListener('message',requested);return()=>window.removeEventListener('message',requested)},[token,catalog,selected,title,period,entities,target,targetFamily,technical,generating,active]);
 async function open(a:Analysis,silent=false){if(!silent)setBusy(true);setError('');try{const data=await call<{url:string}>(token,`/analyses/${a.id}/workbench-session`,'POST',{});setActive(a);setWorkbench(current=>silent&&current?current:data.url);sessionStorage.setItem(activeSessionKey,a.id);return data.url;}catch(e){if(!silent)setError(message(e));return '';}finally{if(!silent)setBusy(false);}}
 useEffect(()=>{if(!analysesLoaded||restored.current)return;restored.current=true;const id=sessionStorage.getItem(activeSessionKey);if(!id)return;const saved=analyses.find(item=>item.id===id&&item.status==='ready');if(saved)void open(saved);else sessionStorage.removeItem(activeSessionKey);},[analysesLoaded,analyses,activeSessionKey]);
 useEffect(()=>{if(!active||active.status!=='ready'||!workbench)return;const renew=()=>void open(active,true);const interval=window.setInterval(renew,5*60*1000);const visible=()=>{if(document.visibilityState==='visible')renew();};document.addEventListener('visibilitychange',visible);return()=>{window.clearInterval(interval);document.removeEventListener('visibilitychange',visible);};},[active?.id,active?.status,workbench,token]);
 async function recoverWorkbench(){if(!active||recovering.current)return;let expired=false;try{const content=frame.current?.contentDocument?.body?.textContent||'';expired=content.includes('renew the workbench session');}catch{return;}if(!expired)return;recovering.current=true;const url=await open(active,true);if(url)setWorkbench(`${url}?resume=${Date.now()}`);recovering.current=false;}
 async function download(id:string,artifact:string){try{const r=await fetch(`/api/analytics/reports/${id}/${artifact}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Download unavailable.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=id+'-'+artifact;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(message(e));}}
 function openAudit(report?:Report){setError('');setAuditNotice('');setAuditTarget(report||null);setAuditCategory(report&&reportCategories.some(([id])=>id===report.family)?report.family:'production_offtake');setAuditPicker(true)}
 function closeAudit(){setAuditPicker(false);setAuditTarget(null)}
 async function submitAudit(){if(!auditTarget)return;setBusy(true);setError('');setAuditNotice('');try{await call(token,`/reports/${auditTarget.id}/audit`,'POST',{category:auditCategory});await refresh();setQuickReport(current=>current?.id===auditTarget.id?{...current,family:auditCategory,audit_status:'pending_review'}:current);setAuditNotice(`${categoryName(auditCategory)} sent to the ${auditTarget.entity} manager for approval.`);closeAudit()}catch(e){setError(message(e))}finally{setBusy(false)}}
 return <div className="analytics-workspace" data-view={view}>
 {view==='inputs'&&<SubmissionWorkspace token={token} entityCode={entityCode} technical={technical} onUploaded={()=>void refresh()}/>} 
 {view==='vault'&&<VaultWorkspace token={token} entityCode={entityCode} canFilterSubsidiary={technical}/>} 
 {view==='extraction'&&!technical&&<AuditWorkspace token={token} position={reviewPosition} onChange={()=>void refresh()}/>}
 {error&&!auditPicker&&(view==='analysis'||view==='reports')&&<div className="error-box" role="alert"><AlertCircle size={18}/>{error}</div>}
 {auditNotice&&!auditPicker&&<p role="status">{auditNotice}</p>}
 {view==='analysis'&&quickReport&&<section className="panel quick-report-result workbench-report-result"><div><h2>Report ready</h2><p>{quickReport.title} · {quickReport.source_family?categoryName(quickReport.source_family):categoryName(quickReport.family)} · {quickReport.entity}</p></div><div className="analytics-actions"><button className="button secondary" onClick={()=>void download(quickReport.id,'report.pdf')}><Download size={15}/>Download PDF</button><button className="button primary" disabled={busy||quickReport.can_submit===false||!!quickReport.audit_status} onClick={()=>openAudit(quickReport)}><ClipboardCheck size={15}/>{quickReport.can_submit===false?'Choose a subsidiary destination':quickReport.audit_status?'Sent for audit':'Send for audit'}</button></div></section>}
 <div className="analytics-content">
 {view==='analysis'&&<>
 <AnalysisDashboard catalog={catalog} technical={technical} entityCode={entityCode} selected={selected} setSelected={setSelected} entities={entities} setEntities={setEntities} family={family} setFamily={setFamily} title={title} setTitle={setTitle} period={period} setPeriod={setPeriod} target={target} setTarget={setTarget} targetFamily={targetFamily} setTargetFamily={setTargetFamily} busy={busy} online={status?.online} modelReady={status?.model_ready} analyses={analyses} onCreate={()=>void create()} onOpen={a=>{setActive(a);if(a.status==='ready')void open(a);}} onRefresh={refresh} token={token} workbenchMode/>
 {!workbench&&<section className="analysis-workbench analysis-workbench-empty">{active?.status==='importing'?<><strong>{active.phase==='extracting'?'Extracting document data…':'Preparing selected data…'}</strong><span>{active.phase==='extracting'&&active.current_source?active.current_source:'Your analytics workspace will open here.'}</span><div className="analysis-progress" role="progressbar" aria-label="Preparing analytics data" aria-valuemin={0} aria-valuemax={100} aria-valuenow={active.progress||0}><i style={{width:`${active.progress||0}%`}}/></div><small>{active.phase==='extracting'&&active.document_total?`Document ${active.document_index||1} of ${active.document_total}${active.page_count?` · page ${active.current_page||0} of ${active.page_count}`:''}`:'Preparing workbench'} · {active.progress||0}%</small></>:active?.status==='failed'?<><AlertCircle size={28}/><strong>Selected data could not be prepared</strong><span>{active.error||'Choose the source again or select another file.'}</span></>:status&&!status.online?<><AlertCircle size={28}/><strong>Analytics is unavailable</strong><span>Check the analytics service and try again.</span></>:<><span className="analysis-empty-icon"><BarChart3 size={24}/></span><strong>Select data to start working with analytics</strong><span>PDFs and images are converted when selected.</span></>}</section>}
 </>}
 {workbench&&active&&<section className="analysis-workbench" hidden={view!=='analysis'}><iframe ref={frame} title="CIL analytics workbench" src={workbench} onLoad={()=>void recoverWorkbench()} allow="fullscreen; clipboard-write"/></section>}
 {view!=='analysis'&&<>
 {quickReport&&<section className="panel quick-report-result"><div><h2>Report ready</h2><p>{quickReport.title} · {quickReport.source_family?categoryName(quickReport.source_family):categoryName(quickReport.family)}{quickReport.source_version?` · source v${quickReport.source_version}`:''} · {quickReport.entity}</p></div><div className="analytics-actions"><button className="button secondary" onClick={()=>void download(quickReport.id,'report.pdf')}><Download size={15}/>Download PDF</button><button className="button primary" disabled={busy||quickReport.can_submit===false||!!quickReport.audit_status} onClick={()=>openAudit(quickReport)}><ClipboardCheck size={15}/>{quickReport.can_submit===false?'Choose a subsidiary destination':quickReport.audit_status?'Sent for audit':'Send for audit'}</button></div></section>}
 {active&&active.status!=='ready'&&<section className="panel analysis-state"><strong>{active.title}</strong><span>{active.status==='importing'?'Preparing the selected data…':active.error||'Analysis unavailable.'}</span></section>}
 {active?.status==='ready'&&<section className="panel analysis-state"><strong>{active.title}</strong><button className="button primary" disabled={busy} onClick={()=>void open(active)}>{busy?'Opening analysis…':<>Open analysis <ArrowRight size={16}/></>}</button></section>}
 </>}
 </div>
 <dialog ref={auditDialog} className="audit-report-picker" onCancel={closeAudit}><header><div><h2>{auditTarget?'Classify report':'Choose a report'}</h2><p>{auditTarget?'Select the category under which this report will be audited and submitted.':'Choose the generated report you want to send.'}</p></div><button className="button secondary" onClick={closeAudit}>Close</button></header>{error&&<p className="error" role="alert">{error}</p>}{auditTarget?<div className="audit-classify"><div className="audit-report-summary"><strong>{auditTarget.title}</strong><span>Subsidiary: {auditTarget.entity}</span><span>Version: v{auditTarget.version||1}</span></div><label className="field">Report category<select value={auditCategory} onChange={event=>setAuditCategory(event.target.value)}>{reportCategories.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><small>This category is shown in the subsidiary audit queue and CMPDI submission list.</small></label><div className="modal-actions"><button className="button secondary" disabled={busy} onClick={()=>setAuditTarget(null)}>Back</button><button className="button primary" disabled={busy} onClick={()=>void submitAudit()}><ClipboardCheck size={16}/>{busy?'Sending…':'Send to subsidiary audit'}</button></div></div>:reports.length?reports.map(r=><div className="saved-analysis" key={r.id}><div><strong>{r.title}</strong><small>{r.entity} · {categoryName(r.family)} · v{r.version||1}</small></div><button className="button primary" disabled={busy||r.can_submit===false||Boolean(r.audit_status&&r.audit_status!=='rejected')} onClick={()=>openAudit(r)}>{r.can_submit===false?'View only':r.audit_status==='rejected'?'Classify & resend':r.audit_status?'Submitted':'Choose category'}</button></div>):<p>Generate a report in the workbench and use Save report. Your saved reports will appear here.</p>}</dialog>
 <div hidden={view!=='reports'}>
 <section className="panel"><div className="section-heading"><div><h2><FileText size={19}/> Submitted reports</h2><p>Approved reports organized by subsidiary, category and version.</p></div><button className="text-button" onClick={()=>void refresh()}>Refresh reports</button></div>{reports.length?reports.map(r=><div className="saved-analysis" key={r.id}><div><strong>{r.title}</strong><small>{r.entity} / {categoryName(r.family)} / v{r.version||1} · {new Date(r.created*1000).toLocaleString()}{r.audit_status?` · ${r.audit_status.replaceAll('_',' ')}`:''}</small></div><div className="analytics-actions">{[['report.pdf','PDF'],['report.zip','Complete package'],['report.png','Visual report'],['report.md','Markdown'],['manifest.json','Sources']].map(([file,label])=><button key={file} className="text-button" onClick={()=>void download(r.id,file)}><Download size={15}/>{label}</button>)}</div></div>):<div className="empty small"><p>No approved reports yet.</p></div>}</section>
 </div></div>;
}
