import {useEffect,useRef,useState,type FormEvent,type ReactNode} from 'react';
import type {Session} from '@supabase/supabase-js';
import {ArrowRight,ArrowUpRight,Building2,Check,ChevronRight,Eye,EyeOff,FileCheck2,Layers3,LayoutDashboard,LockKeyhole,LogOut,Menu,Network,Plus,Search,Settings2,Shield,ShieldCheck,Users,X,MapPin,LoaderCircle,AlertCircle,KeyRound,Activity,Palette} from 'lucide-react';
import {api,configured,previewAvailable,supabase} from './client';
import {previewEntities,previewIdentity} from './preview';
import {ReportingWorkspace} from './ReportingWorkspace';
import {AnalyticsWorkspace} from './AnalyticsWorkspace';
import {VaultWorkspace} from './VaultWorkspace';
import {ModelProviders} from './ModelProviders';
import {accents,Appearance,useAppearance} from './Appearance';
import {WorkspaceBrand,WorkspaceSidebar,WorkspaceHeader,SettingsLayout,type ToolView,type SettingsSection} from './WorkspaceChrome';
import {roleNames,type Entity,type Identity,type Profile,type AccessEvent} from './types';

type Page='overview'|'vault'|'entities'|'people'|'security'|'analytics';
const errorText=(error:unknown)=>error instanceof Error?error.message:'Something went wrong. Please retry.';
const date=(value:string)=>value?new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';
function Brand(_props:{light?:boolean}){return <WorkspaceBrand/>}
function Spinner(){return <LoaderCircle className="spin" size={18}/>}
function Badge({children,tone='green'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}><i/>{children}</span>}
function PasswordField({label,value,onChange,autoComplete='current-password',minLength=1}:{label:string;value:string;onChange:(s:string)=>void;autoComplete?:string;minLength?:number}){
 const [visible,setVisible]=useState(false);return <label className="field">{label}<span className="password-input"><input aria-label={label} type={visible?'text':'password'} value={value} onChange={e=>onChange(e.target.value)} required minLength={minLength} maxLength={128} autoComplete={autoComplete}/><button type="button" aria-label={`${visible?'Hide':'Show'} ${label.toLowerCase()}`} onClick={()=>setVisible(!visible)}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>
}
function Login({onPreview}:{onPreview:()=>void}){
 const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <main className="login"><section className="login-story"><Brand light/><div className="story-body"><span className="eyebrow"><span/> ONE GROUP. A CONNECTED WORKSPACE.</span><h1>A clear view.<br/>A stronger foundation.</h1><p>The shared workspace for Coal India, its operating subsidiaries, and CMPDI.</p><div className="story-diagram"><div className="story-apex"><ShieldCheck/><div><strong>CIL Central</strong><small>Apex administration</small></div><Badge>Holding</Badge></div><div className="story-branches"><div><Building2/><strong>7 operating entities</strong><small>Operational reporting</small></div><div><Network/><strong>CMPDI</strong><small>Technical coordination</small></div></div></div></div><footer><span>COAL INDIA LIMITED</span><span>Enterprise access portal <ArrowUpRight size={14}/></span></footer></section><section className="login-panel"><div className="login-top"><span><LockKeyhole size={15}/> Restricted workspace</span></div><div className="login-form"><div className="intro-icon"><ShieldCheck size={25}/></div><span className="eyebrow blue-text">WELCOME TO CIL CENTRAL</span><h2>Sign in to your workspace</h2><p>Use the account assigned by your CIL administrator.</p>{!configured&&<div className="notice"><Settings2 size={19}/><div><strong>Connect your Supabase project</strong><span>Complete the .env file, run the database migration, and bootstrap the administrator to enable sign-in.</span></div></div>}<form onSubmit={submit}><label className="field">Work email<input type="email" autoComplete="username" required placeholder="you@organisation.in" value={email} onChange={e=>setEmail(e.target.value)}/></label><PasswordField label="Password" value={password} onChange={setPassword}/>{error&&<p role="alert" className="error"><AlertCircle size={17}/>{error}</p>}<button className="button primary full" disabled={busy||!configured}>{busy?<Spinner/>:<>Sign in securely <ArrowRight size={18}/></>}</button></form><div className="login-help"><LockKeyhole size={15}/> Accounts are administrator-provisioned.<br/>For access or password recovery, contact CIL administration.</div>{previewAvailable&&!configured&&<button className="preview-link" onClick={onPreview}>Explore a read-only interface preview <ArrowUpRight size={16}/></button>}</div><footer className="login-foot"><Shield size={15}/> Your entity and permissions are assigned securely.</footer></section></main>
}
function PasswordForm({token,onDone,required=false}:{token:string;onDone:()=>void;required?:boolean}){
 const [current,setCurrent]=useState('');const [next,setNext]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();if(next!==confirm){setError('The new passwords do not match.');return;}setBusy(true);setError('');try{await api('/api/auth/change-password',token,'POST',{current_password:current,new_password:next});onDone();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <form className="password-form" onSubmit={submit}><h3>{required?'Set your own password':'Change password'}</h3><p>{required?'Replace your temporary password before accessing this workspace.':'You will sign in again after changing your password.'} Use at least 14 characters.</p><PasswordField label="Current password" value={current} onChange={setCurrent}/><PasswordField label="New password" value={next} onChange={setNext} autoComplete="new-password" minLength={14}/><PasswordField label="Confirm new password" value={confirm} onChange={setConfirm} autoComplete="new-password" minLength={14}/>{error&&<p className="error" role="alert">{error}</p>}<button className="button primary" disabled={busy}>{busy?<Spinner/>:<KeyRound size={16}/>} Update password</button></form>
}
function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);
 return <dialog ref={ref} onCancel={e=>{e.preventDefault();onClose();}} className="modal"><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></header>{children}</dialog>
}
export default function App(){
 const {preferences,setPreferences}=useAppearance();
 const [toolView,setToolView]=useState<ToolView>('inputs'),[settingsSection,setSettingsSection]=useState<SettingsSection>('overview');
 const [session,setSession]=useState<Session|null>(null);const [loadingAuth,setLoadingAuth]=useState(configured);const [identity,setIdentity]=useState<Identity|null>(null);const [preview,setPreview]=useState(false);const [accessError,setAccessError]=useState('');const [loading,setLoading]=useState(false);const [page,setPage]=useState<Page>('overview');const [entities,setEntities]=useState<Entity[]>([]);const [people,setPeople]=useState<Profile[]>([]);const [events,setEvents]=useState<AccessEvent[]>([]);const [dataError,setDataError]=useState('');const [notice,setNotice]=useState('');const [mobile,setMobile]=useState(false);const [revision,setRevision]=useState(0);const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [modal,setModal]=useState<'member'|'entity'|null>(null);const [editing,setEditing]=useState<Entity|null>(null);const [saving,setSaving]=useState(false);const [modalError,setModalError]=useState('');
 useEffect(()=>{window.scrollTo({top:0});},[page,toolView]);
 useEffect(()=>{if(identity?.profile.role==='cmpdi'&&toolView==='extraction')setToolView('reports');},[identity?.profile.role,toolView]);
 const token=session?.access_token||'';const admin=identity?.profile.role==='cil_admin';
 useEffect(()=>{if(!supabase)return;let active=true;supabase.auth.getSession().then(({data,error})=>{if(active){if(error)setAccessError(error.message);setSession(data.session);setLoadingAuth(false);}}).catch(e=>{if(active){setAccessError(errorText(e));setLoadingAuth(false);}});const {data}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);setLoadingAuth(false);});return()=>{active=false;data.subscription.unsubscribe();};},[]);
 useEffect(()=>{if(preview){setIdentity(previewIdentity);setEntities(previewEntities);setPeople([]);setEvents([]);return;}if(!token){setIdentity(null);setEntities([]);setPeople([]);return;}let current=true;setLoading(true);setIdentity(null);setAccessError('');api<Identity>('/api/me',token).then(me=>{if(current){setIdentity(me);setPage(me.profile.role==='cil_admin'?'overview':'analytics');}}).catch(e=>{if(current)setAccessError(errorText(e));}).finally(()=>{if(current)setLoading(false);});return()=>{current=false;};},[token,preview]);
 useEffect(()=>{if(!identity||preview||identity.profile.must_change_password)return;let current=true;setDataError('');Promise.all([api<Entity[]>('/api/entities',token),...(admin?[api<Profile[]>('/api/admin/users',token),api<AccessEvent[]>('/api/admin/events',token)]:[])]).then(([es,ps,ev])=>{if(current){setEntities(es as Entity[]);setPeople((ps||[]) as Profile[]);setEvents((ev||[]) as AccessEvent[]);}}).catch(e=>{if(current)setDataError(errorText(e));});return()=>{current=false;};},[identity,token,preview,admin,revision]);
 async function signout(message=''){if(session?.access_token){try{await fetch('/api/analytics/workbench-sessions/revoke',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`}});}catch{/* Local sign-out still proceeds when offline. */}}setPreview(false);setIdentity(null);setSession(null);setPage('overview');setNotice(message);if(supabase){await supabase.auth.signOut({scope:'local'});}}
 async function toggleUser(p:Profile){if(preview||saving)return;setSaving(true);setDataError('');try{await api(`/api/admin/users/${p.id}`,token,'PATCH',{active:!p.active});setRevision(x=>x+1);setNotice(`Account ${p.active?'disabled':'enabled'}.`);}catch(e){setDataError(errorText(e));}finally{setSaving(false);}}
 async function updateReviewPosition(p:Profile,review_position:string){if(preview||saving)return;setSaving(true);setDataError('');try{await api(`/api/admin/users/${p.id}/review-position`,token,'PATCH',{review_position});setRevision(x=>x+1);setNotice('Audit responsibility updated.');}catch(e){setDataError(errorText(e));}finally{setSaving(false);}}
 function openModal(kind:'member'|'entity',entity:Entity|null=null){if(preview){setNotice('Read-only preview. Connect Supabase to manage real accounts and entities.');return;}setEditing(entity);setModalError('');setModal(kind);}
 async function saveForm(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);setSaving(true);setModalError('');try{if(modal==='member'){await api('/api/admin/users',token,'POST',{email:form.get('email'),full_name:form.get('name'),entity_id:form.get('entity'),temporary_password:form.get('password'),review_position:form.get('review_position')});setNotice('Account created. Share the temporary password securely; the member must change it at first sign-in.');}else{await api(editing?`/api/admin/entities/${editing.id}`:'/api/admin/entities',token,editing?'PATCH':'POST',{code:form.get('code'),name:form.get('name'),location:form.get('location'),active:form.get('active')==='on'});setNotice('Entity details saved.');}setModal(null);setRevision(x=>x+1);}catch(e){setModalError(errorText(e));}finally{setSaving(false);}}
 if(loadingAuth||loading)return <div className="loading-screen"><Brand/><Spinner/><p>Verifying your workspace access…</p></div>;
 if(!session&&!preview)return <><Login onPreview={()=>{setPreview(true);setAccessError('');}}/>{notice&&<div className="toast" role="status">{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}</>;
 if(accessError||!identity)return <div className="access-screen"><Shield size={38}/><h1>Workspace access unavailable</h1><p role="alert">{accessError||'Your membership could not be loaded.'}</p><button className="button primary" onClick={()=>void signout()}>Back to sign in</button></div>;
 if(identity.profile.must_change_password)return <div className="first-password"><Brand/><div className="panel"><PasswordForm token={token} required onDone={()=>void signout('Password updated. Sign in with your new password.')}/><button className="text-button" onClick={()=>void signout()}>Sign out</button></div></div>;
 const subsidiaries=entities.filter(e=>e.kind!=='holding');const operating=subsidiaries.filter(e=>e.kind==='operating');const technical=subsidiaries.find(e=>e.kind==='technical');
 const visibleEntities=subsidiaries.filter(e=>(filter==='all'||e.kind===filter)&&`${e.name} ${e.code} ${e.location}`.toLowerCase().includes(query.toLowerCase()));
 const isTechnical=identity.profile.role==='cmpdi';
 const overviewTitle=admin?'Dashboard':isTechnical?'Technical coordination':'Production reporting';
 const directoryTitle=admin?'Entity master':isTechnical?'Reporting subsidiaries':'My subsidiary';
 const toolTitle={inputs:'Upload',vault:'Vault',analysis:'Analyse',extraction:'Audit',reports:'Submission'}[toolView];
 const title={overview:overviewTitle,vault:'Vault',entities:directoryTitle,people:'Access & people',security:'Settings',analytics:toolTitle}[page];
 const profile=()=>{setSettingsSection('profile');setPage('security');};
 const tool=(view:ToolView)=>{setToolView(view);setPage('analytics');};
 const headerAction=admin&&(page==='entities'||page==='people')?<button className="button primary" aria-label={page==='entities'?'Add entity':'Add member'} onClick={()=>openModal(page==='entities'?'entity':'member')}><Plus size={17}/><span className="button-label">{page==='entities'?'Add entity':'Add member'}</span></button>:undefined;
 return <div className={`app-shell role-${identity.profile.role}`}><a className="skip-link" href="#workspace-content">Skip to main content</a><WorkspaceSidebar identity={identity} page={page} view={toolView} onPage={value=>{setPage(value as Page);if(value==='security')setSettingsSection('overview');setQuery('');setFilter('all');}} onTool={tool} onProfile={profile} onSignout={()=>void signout()} mobile={mobile} onClose={()=>setMobile(false)}/>
 <div className="main-shell"><WorkspaceHeader title="" identity={identity} dark={preferences.mode==='dark'} onTheme={()=>setPreferences({...preferences,mode:preferences.mode==='dark'?'light':'dark'})} onMenu={()=>setMobile(true)} onProfile={profile} action={headerAction}/>
 {preview&&<div className="preview-banner"><Eye size={16}/><span><strong>Read-only design preview.</strong> Sample entity data; no live session, accounts or changes.</span><button onClick={()=>void signout()}>Exit preview <X size={14}/></button></div>}
 <main id="workspace-content" className="workspace-main" tabIndex={-1}>
 {!(page==='analytics'&&toolView==='inputs')&&<header className="workspace-page-heading"><h1>{title}</h1></header>}
 {dataError&&<div className="error-box" role="alert"><AlertCircle size={18}/>{dataError}<button className="text-button" onClick={()=>setRevision(x=>x+1)}>Retry</button></div>}
 {page==='overview'&&!admin&&<ReportingWorkspace entity={identity.entity} technical={isTechnical} entities={entities} onOpenReports={()=>tool('inputs')}/>}
 {page==='overview'&&admin&&<><div className="stat-grid"><Stat label="Connected entities" value={subsidiaries.length} note={admin?'Under CIL administration':'Within your access scope'} icon={<Building2/>}/><Stat label="Operating subsidiaries" value={operating.length} note="Operational reporting entities" icon={<Network/>}/><Stat label="Technical coordinator" value={technical?1:0} note={technical?'CMPDI · Technical & planning':'Own entity access'} icon={<Layers3/>}/><Stat label={admin?'Apex administrator':'Your access'} value={admin?'01':identity.entity.code} note={admin?'Single protected administrator':roleNames[identity.profile.role]} icon={<ShieldCheck/>}/></div>
 <div className="overview-layout"><section className="panel hierarchy-panel"><div className="section-heading"><div><span className="eyebrow">ORGANISATIONAL STRUCTURE</span><h2>{admin||identity.profile.role==='cmpdi'?'One group. Clear responsibilities.':'Your place in the group.'}</h2></div><span className="subtle-pill">Access hierarchy</span></div><div className="hierarchy"><div className="apex-node"><span className="entity-icon navy"><ShieldCheck/></span><div><strong>CIL Central Admin</strong><span>Apex / holding administration</span></div><LockKeyhole size={16}/></div><div className="connector-line"/><div className="branch-cards">{technical&&<div className="branch technical"><span className="entity-icon blue"><Layers3/></span><Badge tone="blue">Technical & planning</Badge><h3>CMPDI</h3><p>Technical coordination, exploration and quality assurance.</p><span className="branch-footer">Reports to CIL <ArrowUpRight size={16}/></span></div>}<div className="branch operations"><span className="entity-icon amber"><Building2/></span><Badge tone="amber">Operational entities</Badge><h3>{operating.length===1?operating[0].code:`${operating.length} operating subsidiaries`}</h3><div className="entity-chips">{operating.map(e=><span key={e.id}>{e.code}</span>)}</div><span className="branch-footer">Production inputs → CMPDI → CIL</span></div></div></div></section>
 <section className="panel access-panel"><span className="eyebrow">YOUR WORKSPACE</span><h2>Access at a glance</h2><div className="role-tile"><ShieldCheck size={24}/><strong>{roleNames[identity.profile.role]}</strong><Badge>Active</Badge></div><ul className="access-list">{(admin?['Manage entity master','Provision subsidiary accounts','Suspend or restore member access','Single apex authority']:identity.profile.role==='cmpdi'?['View all group entities','Technical coordinator membership','Manage your own password','No administrator privileges']:['Access your assigned entity','Own subsidiary membership','Manage your own password','No cross-subsidiary access']).map(x=><li key={x}><Check size={16}/>{x}</li>)}</ul><button className="button secondary full" onClick={profile}>View account details <ArrowRight size={16}/></button></section></div>
 <EntityTable entities={subsidiaries} people={people} canEdit={!!admin} onEdit={e=>openModal('entity',e)} onViewAll={()=>setPage('entities')} compact/>
 </>}
 {page==='vault'&&admin&&<VaultWorkspace token={token} entityCode="CIL" canFilterSubsidiary/>}
 {page==='entities'&&<>{!admin&&<div className="reporting-directory-note">{isTechnical?'Production subsidiaries submit reports to CMPDI for technical processing. CIL administers all entities.':`${identity.entity.code} submits reports to CMPDI. CIL Central Admin manages the group and your account access.`}</div>}<div className="directory-toolbar"><div className="filter-tabs">{[['all','All entities'],['operating','Operating'],['technical','Technical']].map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={filter===key?'selected':''}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="Search entities" placeholder="Search entities…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><EntityTable entities={visibleEntities} people={people} canEdit={!!admin} onEdit={e=>openModal('entity',e)}/></>}
 {page==='people'&&admin&&<section className="panel"><div className="section-heading"><div><h2>Workspace members</h2></div><Badge tone="blue">{preview?'Sample view':`${people.length} accounts`}</Badge></div><div className="table-wrap"><table><thead><tr><th>Member</th><th>Entity</th><th>Role</th><th>Audit position</th><th>Status</th><th>Access</th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><strong>{p.full_name}</strong><small>{p.email}</small></td><td>{entities.find(e=>e.id===p.entity_id)?.code||'—'}</td><td>{roleNames[p.role]}</td><td>{p.role==='subsidiary'?<select aria-label={`Audit position for ${p.full_name}`} disabled={saving||preview} value={p.review_position||'contributor'} onChange={e=>void updateReviewPosition(p,e.target.value)}><option value="contributor">Contributor</option><option value="assistant_manager">Assistant manager</option><option value="manager">Manager</option></select>:'—'}</td><td><Badge tone={p.active?'green':'gray'}>{p.active?(p.must_change_password?'First sign-in pending':'Active'):'Disabled'}</Badge></td><td>{p.role==='cil_admin'?<span className="protected"><LockKeyhole size={14}/> Protected</span>:<button className="text-button" disabled={saving} onClick={()=>void toggleUser(p)}>{p.active?'Disable':'Enable'}</button>}</td></tr>)}</tbody></table>{people.length===0&&<div className="empty"><Users size={28}/><h3>{preview?'Your team will appear here':'No accounts to display'}</h3><p>{preview?'Connect Supabase and bootstrap the administrator to provision members.':'Refresh the directory after provisioning a member.'}</p></div>}</div><div className="panel-foot"><KeyRound size={16}/> New members must replace their temporary password at first sign-in. No public registration.</div></section>}
 {!admin&&<div hidden={page!=='analytics'}><AnalyticsWorkspace token={token} entityCode={identity.entity.code} technical={isTechnical} view={toolView} reviewPosition={identity.profile.review_position}/></div>}
 {page==='security'&&<SettingsLayout section={settingsSection} onSection={setSettingsSection} admin={!!admin} canManageModels={isTechnical} onEntities={()=>setPage('entities')} onPeople={()=>setPage('people')}>
  {settingsSection==='overview'&&<div className="settings-overview"><section className="panel settings-group"><div className="section-heading"><div><h2>Account</h2><p>Profile, sign-in and display preferences</p></div></div><div className="settings-links"><button onClick={()=>setSettingsSection('profile')}><UserSummary identity={identity}/><ChevronRight size={18}/></button><button onClick={()=>setSettingsSection('security')}><span className="settings-link-icon"><Shield size={19}/></span><span><strong>Login &amp; security</strong><small>Change your password</small></span><ChevronRight size={18}/></button><button onClick={()=>setSettingsSection('appearance')}><span className="settings-link-icon"><Palette size={19}/></span><span><strong>Appearance</strong><small>{preferences.mode==='dark'?'Dark':'Light'} mode · {accents.find(accent=>accent.id===preferences.accent)?.name}</small></span><ChevronRight size={18}/></button></div></section><section className="panel settings-group"><div className="section-heading"><div><h2>Workspace</h2><p>{admin?'Manage the organisation and access':'View your reporting organisation'}</p></div></div><div className="settings-links"><button onClick={()=>setPage('entities')}><span className="settings-link-icon"><Building2 size={19}/></span><span><strong>{admin?'Entity master':'Subsidiaries'}</strong><small>{admin?`${subsidiaries.length} connected entities`:'Your authorised entity directory'}</small></span><ChevronRight size={18}/></button>{admin&&<button onClick={()=>setPage('people')}><span className="settings-link-icon"><Users size={19}/></span><span><strong>Team members</strong><small>{preview?'Account access and roles':`${people.length} workspace accounts`}</small></span><ChevronRight size={18}/></button>}</div></section></div>}
  {settingsSection==='profile'&&<section className="panel profile-panel"><div className="section-heading"><div><h2>Your profile</h2><p>Identity and workspace access</p></div><ShieldCheck className="blue-text"/></div><dl className="details"><dt>Full name</dt><dd>{identity.profile.full_name}</dd><dt>Email</dt><dd>{identity.profile.email}</dd><dt>Entity</dt><dd>{identity.entity.name}</dd><dt>Role</dt><dd>{roleNames[identity.profile.role]}</dd><dt>Account status</dt><dd><Badge>Active</Badge></dd></dl></section>}
  {settingsSection==='security'&&<div className="security-grid"><section className="panel password-panel">{preview?<div className="empty"><KeyRound size={30}/><h3>Password management</h3><p>Available for your authenticated account once Supabase is connected.</p></div>:<PasswordForm token={token} onDone={()=>void signout('Password updated. Sign in with your new password.')}/>}</section>{admin&&<section className="panel audit-panel"><div className="section-heading"><div><h2>Recent access changes</h2><p>Account and entity administration events</p></div><Activity size={20}/></div>{events.length?events.map(ev=><div className="event" key={ev.id}><span className="event-dot"/><div><strong>{ev.action.replaceAll('.',' · ')}</strong><small>{ev.target}</small></div><time>{date(ev.created_at)}</time></div>):<div className="empty small"><p>No access changes recorded yet.</p></div>}</section>}</div>}
  {settingsSection==='appearance'&&<Appearance preferences={preferences} onChange={setPreferences}/>} 
  {settingsSection==='models'&&isTechnical&&<ModelProviders token={token} onChange={()=>setNotice('AI provider settings updated.')}/>} 
 </SettingsLayout>}
 </main></div>
 {notice&&<div className="toast" role="status"><Check size={18}/><span>{notice}</span><button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {modal&&<Modal title={modal==='member'?'Provision a member':editing?'Edit entity':'Add operating entity'} onClose={()=>{if(!saving)setModal(null);}}><form onSubmit={saveForm}>{modal==='member'?<><p className="modal-description">Assign a person to an operating subsidiary or CMPDI. Their role follows the entity; administrator access cannot be assigned.</p><label className="field">Full name<input name="name" required minLength={2} maxLength={100} autoComplete="off"/></label><label className="field">Work email<input name="email" type="email" required autoComplete="off"/></label><label className="field">Entity<select name="entity" required defaultValue=""><option value="" disabled>Select an entity</option>{subsidiaries.filter(e=>e.active).map(e=><option key={e.id} value={e.id}>{e.code} — {e.kind==='technical'?'Technical coordinator':'Subsidiary member'}</option>)}</select></label><label className="field">Audit position<select name="review_position" defaultValue="contributor"><option value="contributor">Contributor</option><option value="assistant_manager">Assistant manager</option><option value="manager">Manager</option></select><small>Audit positions apply to subsidiary members.</small></label><label className="field">Temporary password<input name="password" type="password" required minLength={14} maxLength={128} autoComplete="new-password"/><small>At least 14 characters. Share securely outside this application.</small></label></>:<><label className="field">Entity code<input name="code" required pattern="[A-Z][A-Z0-9_]{1,15}" defaultValue={editing?.code||''} readOnly={!!editing} maxLength={16}/></label><label className="field">Full entity name<input name="name" required minLength={2} maxLength={160} defaultValue={editing?.name||''}/></label><label className="field">Location<input name="location" maxLength={100} defaultValue={editing?.location||''}/></label><label className="checkbox"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Entity is active</label><p className="modal-description">Disabling an entity blocks its members from accessing the workspace.</p></>}{modalError&&<p className="error" role="alert">{modalError}</p>}<div className="modal-actions"><button className="button secondary" type="button" disabled={saving} onClick={()=>setModal(null)}>Cancel</button><button className="button primary" disabled={saving}>{saving?<Spinner/>:<Check size={17}/>} {modal==='member'?'Create account':'Save entity'}</button></div></form></Modal>}
 </div>
}
function Stat({label,value,note,icon}:{label:string;value:number|string;note:string;icon:ReactNode}){return <div className="stat"><div><span>{label}</span><div className="stat-icon">{icon}</div></div><strong>{typeof value==='number'?String(value).padStart(2,'0'):value}</strong><small>{note}</small></div>}
function UserSummary({identity}:{identity:Identity}){return <><span className="settings-link-icon"><Users size={19}/></span><span><strong>Your profile</strong><small>{identity.profile.full_name} · {identity.entity.code}</small></span></>}
function EntityTable({entities,people,canEdit,onEdit,onViewAll,compact=false}:{entities:Entity[];people:Profile[];canEdit:boolean;onEdit:(e:Entity)=>void;onViewAll?:()=>void;compact?:boolean}){return <section className="panel entity-table"><div className="section-heading"><div><h2>{compact?'Connected entities':'Entity directory'}</h2></div>{onViewAll&&<button className="text-button" onClick={onViewAll}>View all entities <ArrowUpRight size={16}/></button>}</div><div className="table-wrap"><table><thead><tr><th>Entity</th><th>Classification</th><th>Location</th>{canEdit&&<th>Members</th>}<th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{entities.map(e=><tr key={e.id}><td><div className="entity-cell"><span className={`entity-monogram ${e.kind==='technical'?'technical':''}`}>{e.code.slice(0,2)}</span><div><strong>{e.code}</strong><small>{e.name}</small></div></div></td><td><span className={`type-label ${e.kind==='technical'?'blue-text':''}`}>{e.kind==='technical'?'Technical & planning':'Operating subsidiary'}</span></td><td><span className="location"><MapPin size={13}/>{e.location||'—'}</span></td>{canEdit&&<td>{people.filter(p=>p.entity_id===e.id).length}</td>}<td><Badge tone={e.active?'green':'gray'}>{e.active?'Active':'Inactive'}</Badge></td><td>{canEdit&&<button className="icon-button" title={`Edit ${e.code}`} aria-label={`Edit ${e.code}`} onClick={()=>onEdit(e)}><Settings2 size={16}/></button>}</td></tr>)}</tbody></table>{!entities.length&&<div className="empty"><Search size={24}/><h3>No entities found</h3><p>Try another search or filter.</p></div>}</div></section>}
