import {useEffect,useState} from 'react';
import {ScanText,RefreshCw,Check,Download} from 'lucide-react';
type Artifact={name:string;kind:string;rows:number;approved:boolean};
type Job={id:string;entity:string;filename:string;submission_id:string;status:string;error?:string;page_count?:number;pages:{page:number;preview?:string;confidence?:number;status:string;error?:string}[];artifacts:Artifact[]};
type Source={id:string;entity:string;version:number;period:string;cadence:string;files:{name:string;status:string}[]};
export function ExtractionWorkspace({token,onChange}:{token:string;onChange:()=>void}){
 const [jobs,setJobs]=useState<Job[]>([]),[sources,setSources]=useState<Source[]>([]),[engine,setEngine]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selection,setSelection]=useState<{job:Job;artifact:Artifact;rows:string[][];truncated:boolean}|null>(null),[image,setImage]=useState(''),[editing,setEditing]=useState(false),[csv,setCsv]=useState('');
 async function request(path:string,body?:unknown){const r=await fetch('/api/analytics'+path,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(typeof data.detail==='string'?data.detail:'Extraction request failed.');return data;}
 async function refresh(){try{const [result,submissions]=await Promise.all([request('/extractions'),request('/submissions')]);setJobs(result.jobs);setEngine(result.engine_available);setSources(submissions);}catch(e){setError(e instanceof Error?e.message:'Could not load extraction status.');}}
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),4000);return()=>clearInterval(timer);},[token]);
 useEffect(()=>()=>{if(image)URL.revokeObjectURL(image);},[image]);
 async function start(source:Source,name:string){setBusy(true);setError('');try{await request('/extractions',{submission_id:source.id,filename:name});await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not start OCR.');}finally{setBusy(false);}}
 async function open(job:Job,artifact:Artifact){setBusy(true);setError('');setEditing(false);setImage('');try{const data=await request(`/extractions/${job.id}/preview?name=${encodeURIComponent(artifact.name)}`);setSelection({job,artifact,...data});setCsv(data.rows.map((r:string[])=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'));const pageNumber=Number(artifact.name.match(/^page-(\d+)/)?.[1]);const page=job.pages.find(p=>p.page===pageNumber);if(page?.preview){const response=await fetch(`/api/analytics/extractions/${job.id}/artifact?name=${encodeURIComponent(page.preview)}`,{headers:{Authorization:`Bearer ${token}`}});if(response.ok)setImage(URL.createObjectURL(await response.blob()));}}catch(e){setError(e instanceof Error?e.message:'Preview failed.');}finally{setBusy(false);}}
 async function approve(){if(!selection)return;setBusy(true);setError('');try{await request(`/extractions/${selection.job.id}/approve`,{name:selection.artifact.name,corrected_csv:editing?csv:null});setSelection(null);setImage('');await refresh();onChange();}catch(e){setError(e instanceof Error?e.message:'Review could not be saved.');}finally{setBusy(false);}}
 async function download(job:Job,a:Artifact){try{const r=await fetch(`/api/analytics/extractions/${job.id}/artifact?name=${encodeURIComponent(a.name)}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw Error('Download unavailable.');const url=URL.createObjectURL(await r.blob());const link=document.createElement('a');link.href=url;link.download=a.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Download failed.');}}
 return <section className="panel extraction-workspace"><div className="section-heading"><div><h2><ScanText size={19}/> Document extraction</h2><p>Check extracted tables against the original.</p></div><button className="text-button" onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh</button></div>
 {!engine&&<div className="notice">Local OCR engine unavailable. Install Tesseract on the backend host.</div>}{error&&<p className="error" role="alert">{error}</p>}
 {sources.flatMap(source=>source.files.filter(f=>/\.(pdf|png|jpe?g|tiff?)$/i.test(f.name)).map(file=>{const job=jobs.find(j=>j.submission_id===source.id&&j.filename===file.name);return <div className="extraction-source" key={source.id+file.name}><div><strong>{file.name}</strong><small>{source.entity} · {source.cadence} {source.period} · v{source.version} · {job?job.status.replaceAll('_',' '):'Not yet processed'}{job?.page_count?` · ${job.pages.length}/${job.page_count} pages`:''}</small>{job?.error&&<p className="error">{job.error}</p>}{job?.pages.filter(p=>p.error).map(p=><small key={p.page}>Page {p.page}: {p.error}</small>)}</div><button className="button secondary" disabled={busy||['queued','running'].includes(job?.status||'')} onClick={()=>void start(source,file.name)}>{job?'Run again':'Extract document'}</button>{job?.artifacts.length? <div className="extraction-artifacts">{job.artifacts.filter(a=>a.kind!=='word_positions').map(a=><div key={a.name}><span>{a.kind==='table_candidate'?'Table candidate':'Page text'} · {a.name} · {a.rows} rows {a.approved?'· Reviewed':''}</span><button className="text-button" disabled={busy} onClick={()=>void open(job,a)}>Review</button><button className="icon-button" aria-label={`Download ${a.name}`} onClick={()=>void download(job,a)}><Download size={16}/></button></div>)}</div>:null}</div>;}))}
 {!sources.some(s=>s.files.some(f=>/\.(pdf|png|jpe?g|tiff?)$/i.test(f.name)))&&<div className="empty small"><ScanText size={26}/><p>Upload a ZIP containing PDFs or screenshots to start extraction.</p></div>}
 {selection&&<div className="extraction-review"><div className="section-heading"><div><h3>Review {selection.artifact.name}</h3><p>Verify headings, units and values before approval.</p></div><button className="text-button" onClick={()=>{setSelection(null);setImage('');}}>Close review</button></div><div className="review-columns"><div>{image&&<img src={image} alt={`Source page for ${selection.artifact.name}`}/>}</div><div>{editing?<textarea aria-label="Corrected CSV" value={csv} onChange={e=>setCsv(e.target.value)}/>:<div className="table-wrap"><table><thead><tr>{selection.rows[0]?.map((cell,i)=><th key={i}>{cell}</th>)}</tr></thead><tbody>{selection.rows.slice(1).map((row,i)=><tr key={i}>{row.map((cell,k)=><td key={k}>{cell}</td>)}</tr>)}</tbody></table></div>}{selection.truncated&&<p>Showing the first 200 rows. Download the complete CSV before approving.</p>}<div className="analytics-actions"><button className="button secondary" disabled={busy||selection.truncated||selection.artifact.approved} onClick={()=>setEditing(!editing)}>{editing?'Show original preview':'Edit CSV / column headers'}</button><button className="button primary" disabled={busy||selection.artifact.approved} onClick={()=>void approve()}><Check size={16}/>{selection.artifact.approved?'Already reviewed':'Approve for analytics'}</button></div></div></div></div>}
 </section>;
}
