import {useEffect,useState,type FormEvent} from 'react';
import {KeyRound,Plus,Trash2} from 'lucide-react';
type Provider={id:string;name:string;kind:string;models:string[];api_base:string;role?:'standard'|'primary'|'fallback';timeout_seconds?:number};
export function ModelProviders({token,onChange}:{token:string;onChange:()=>void}){
 const [items,setItems]=useState<Provider[]>([]),[endpoint,setEndpoint]=useState('openai'),[name,setName]=useState(''),[models,setModels]=useState(''),[key,setKey]=useState(''),[base,setBase]=useState(''),[version,setVersion]=useState(''),[role,setRole]=useState<'standard'|'primary'|'fallback'>('standard'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/cmpdi/providers',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not load model providers.');setItems(await r.json());}catch(e){setError(e instanceof Error?e.message:'Provider request failed.');}}
 useEffect(()=>{void load();},[token]);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/cmpdi/providers',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name,endpoint,models:models.split(',').map(s=>s.trim()).filter(Boolean),api_key:key,api_base:base,api_version:version,role,timeout_seconds:role==='primary'?18:45})});const d=await r.json();if(!r.ok)throw new Error(typeof d.detail==='string'?d.detail:'Invalid provider settings.');setKey('');setName('');setModels('');await load();onChange();}catch(e){setError(e instanceof Error?e.message:'Provider save failed.');}finally{setBusy(false);}}
 async function remove(id:string){setBusy(true);setError('');try{const r=await fetch('/api/cmpdi/providers/'+id,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Could not remove provider.');await load();onChange();}catch(e){setError(e instanceof Error?e.message:'Removal failed.');}finally{setBusy(false);}}
 return <section className="panel model-providers" aria-labelledby="model-provider-title"><div className="section-heading"><div><h2 id="model-provider-title"><KeyRound size={18}/> AI providers &amp; models</h2><p>Manage the shared model connection used by Analyse.</p></div><span>{items.length} configured locally</span></div><div className="analysis-setup"><p>Primary and fallback providers appear in Analyse as one low-latency CIL Auto model.</p>{error&&<p className="error" role="alert">{error}</p>}{items.map(p=><div className="saved-analysis" key={p.id}><div><strong>{p.name}</strong><small>{p.role&&p.role!=='standard'?`${p.role} · `:''}{p.kind} · {p.models.join(', ')}</small></div><button className="text-button" disabled={busy} onClick={()=>void remove(p.id)}><Trash2 size={15}/>Remove</button></div>)}<form onSubmit={submit}><div className="analysis-fields"><label className="field">Provider<select value={endpoint} onChange={e=>{setEndpoint(e.target.value);setBase(e.target.value==='ollama'?'http://localhost:11434':'');setKey('');setVersion('');}}><option value="openai">OpenAI</option><option value="azure">Azure OpenAI</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option><option value="ollama">Ollama (local or remote)</option><option value="compatible">Third-party · OpenAI-compatible</option></select></label><label className="field">Use as<select value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="standard">Standalone model</option><option value="primary">Primary · fast path</option><option value="fallback">Fallback · on failure</option></select></label><label className="field">Display name<input required minLength={2} maxLength={70} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Team analytics provider"/></label><label className="field">Model identifiers<input required value={models} onChange={e=>setModels(e.target.value)} placeholder="Comma-separated model IDs from your provider"/><small>Only the first model is used in an automatic failover role.</small></label><label className="field">API key {endpoint==='ollama'?'(optional)':''}<input type="password" required={endpoint!=='ollama'} autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><label className="field">API base URL {['azure','compatible','ollama'].includes(endpoint)?'':'(optional)'}<input type="url" required={['azure','compatible','ollama'].includes(endpoint)} value={base} onChange={e=>setBase(e.target.value)} placeholder="https://your-provider.example/v1"/></label>{endpoint==='azure'&&<label className="field">Azure API version<input required value={version} onChange={e=>setVersion(e.target.value)}/></label>}</div><button className="button secondary" disabled={busy}><Plus size={16}/>{busy?'Saving…':'Add provider'}</button><p>Changes are available the next time Analyse opens.</p></form></div></section>;
}
