import {useEffect,useRef,useState} from 'react';
import {Upload,History,ArrowLeft,Download,Clock3,FolderArchive,FileArchive,ArrowRight,Check,X,FileCheck2} from 'lucide-react';
import {uploadZip} from './uploadZip';
type Cycle={last_update:string|null;current_period:string;due_at:string;status:string;latest_version:number|null;previous_period:string;previous_period_status:string;pending_extraction:boolean};
type Family={name:string;last_update:string|null;cycles:Record<string,Cycle>};
type Schedule={subsidiaries:Record<string,Record<string,Family>>;policy:string};
type Submission={id:string;entity:string;family:string;cadence:string;period:string;version:number;uploaded_at:string;pending_extraction:number;needs_review?:number;files:{name:string;bytes:number;status:string}[];previous_id:string|null};
const steps=['Report','Package','Review','Submit'];
const when=(value:string)=>new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'});
export function SubmissionWorkspace({token,entityCode,technical,onUploaded}:{token:string;entityCode:string;technical:boolean;onUploaded:()=>void}){
 const [schedule,setSchedule]=useState<Schedule|null>(null),[history,setHistory]=useState<Submission[]>([]),[entity,setEntity]=useState(technical?'BCCL':entityCode),[family,setFamily]=useState('production_offtake'),[cadence,setCadence]=useState('daily'),[period,setPeriod]=useState(''),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[progress,setProgress]=useState(0),[wizard,setWizard]=useState(false),[step,setStep]=useState(0),[confirmed,setConfirmed]=useState(false),[complete,setComplete]=useState(false),[search,setSearch]=useState(''),[showVersions,setShowVersions]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),focusStep=useRef<HTMLHeadingElement>(null);
 const headers={Authorization:'Bearer '+token};
 async function refresh(){try{const [s,h]=await Promise.all([fetch('/api/analytics/schedules',{headers}),fetch('/api/analytics/submissions',{headers})]);if(!s.ok||!h.ok)throw Error('Could not load submission history.');setSchedule(await s.json());setHistory(await h.json());}catch(e){setError(e instanceof Error?e.message:'Request failed.');}}
 useEffect(()=>{void refresh();},[token]);
 useEffect(()=>{if(wizard)dialog.current?.showModal();else dialog.current?.close();},[wizard]);
 useEffect(()=>{if(wizard)focusStep.current?.focus();},[step,wizard]);
 const families=schedule?.subsidiaries[entity]||{},cycles=families[family]?.cycles||{};
 useEffect(()=>{if(cycles[cadence])setPeriod(cycles[cadence].current_period);},[entity,family,cadence,cycles[cadence]?.current_period]);
 function openWizard(){setStep(0);setComplete(false);setConfirmed(false);setError('');setNotice('');setFile(null);setWizard(true);}
 function chooseFile(value:File|null){setError('');setConfirmed(false);if(value&&(!value.name.toLowerCase().endsWith('.zip')||value.size>256*1024**2||value.size===0)){setFile(null);setError('Choose a non-empty ZIP file up to 256 MiB.');return;}setFile(value);}
 function next(){setError('');if(step===0){const pattern={daily:/^\d{4}-\d{2}-\d{2}$/,monthly:/^\d{4}-\d{2}$/,quarterly:/^\d{4}-Q[1-4]$/,'half-yearly':/^\d{4}-H[12]$/,annual:/^\d{4}$/}[cadence];if(!pattern?.test(period)){setError('Enter the reporting period in the format shown below.');return;}}setStep(s=>s+1);}
 async function submit(){if(!file||busy)return;setBusy(true);setProgress(0);setError('');try{const d=await uploadZip(file,new URLSearchParams({family,cadence,period,...(technical?{entity}:{})}),token,setProgress);const supporting=d.files.filter(f=>f.status==='supporting_document').length;setNotice('Version '+d.version+' stored for '+d.period+'. '+d.files.length+' files preserved'+(supporting?', including '+supporting+' supporting document(s)':'')+'.'+(d.pending_extraction?' PDF/image extraction is queued. Review the results in AUDIT.':' Your structured files are available in ALALYSE.'));setComplete(true);await refresh();onUploaded();}catch(e){setError(e instanceof Error?e.message:'Upload failed.');}finally{setBusy(false);}}
 async function download(id:string){try{const r=await fetch('/api/analytics/submissions/'+id+'/archive',{headers});if(!r.ok)throw Error('Archive unavailable.');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=id+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){setError(e instanceof Error?e.message:'Download failed.');}}
 const records=history.filter(h=>h.entity===entity&&h.family===family&&(h.period+' '+h.files.map(f=>f.name).join(' ')).toLowerCase().includes(search.toLowerCase()));
 const existing=history.filter(h=>h.entity===entity&&h.family===family&&h.cadence===cadence&&h.period===period).sort((a,b)=>b.version-a.version)[0];
 const format={daily:'YYYY-MM-DD',monthly:'YYYY-MM',quarterly:'YYYY-Q1','half-yearly':'YYYY-H1',annual:'YYYY'}[cadence];
 return <div className="submission-workspace">
  {!showVersions?<div className="upload-toolbar">
   {technical&&<label className="field upload-entity">Subsidiary<select disabled={!schedule} value={entity} onChange={e=>{const next=e.target.value;setEntity(next);const nextFamilies=schedule?.subsidiaries[next]||{};const nextFamily=Object.keys(nextFamilies)[0]||'production_offtake';setFamily(nextFamily);setCadence(Object.keys(nextFamilies[nextFamily]?.cycles||{})[0]||'daily');}}>{Object.keys(schedule?.subsidiaries||{}).map(x=><option key={x}>{x}</option>)}</select></label>}
   <label className="field upload-family">Report family<select disabled={!schedule} value={family} onChange={e=>{setFamily(e.target.value);setCadence(Object.keys(families[e.target.value].cycles)[0]);}}>{!schedule&&<option>Loading…</option>}{Object.entries(families).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select></label>
   <button className="button secondary version-control-link" onClick={()=>{setError('');setShowVersions(true);}}><History size={16}/>Version Control</button>
   <section className="panel upload-entry" aria-labelledby="upload-entry-title"><span className="upload-entry-icon"><Upload size={30}/></span><h2 id="upload-entry-title">Upload a report package</h2><p>Send a versioned ZIP package for <strong>{entity}</strong> · {families[family]?.name||'selected report family'}.</p><button className="button primary upload-entry-button" disabled={!schedule} onClick={openWizard}><Upload size={18}/>Choose ZIP package</button><div className="upload-entry-guidance"><span>Inside the ZIP: CSV, Excel, JSON or Parquet data</span><span>Optional: PDF, images and text notes</span><span>Maximum package size: 256 MiB</span></div></section>
  </div>:<div className="version-control-view">
  <header className="version-control-heading"><button className="text-button" onClick={()=>setShowVersions(false)}><ArrowLeft size={16}/>Back to Upload</button><h2>Version Control</h2></header>
  <section className="panel"><div className="vault-filters">{technical&&<label className="field">Subsidiary<select value={entity} onChange={e=>setEntity(e.target.value)}>{Object.keys(schedule?.subsidiaries||{}).map(x=><option key={x}>{x}</option>)}</select></label>}<label className="field">Report family<select value={family} onChange={e=>{setFamily(e.target.value);setCadence(Object.keys(families[e.target.value].cycles)[0]);}}>{Object.entries(families).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select></label><button className="text-button" onClick={()=>void refresh()}>Refresh</button></div>
  <details className="version-schedule"><summary>Reporting schedule</summary><div className="submission-cycles">{Object.entries(cycles).map(([key,c])=><article key={key}><span className="eyebrow"><Clock3 size={14}/> {key}</span><h3>{c.current_period}</h3><strong>{c.status==='submitted'?'Submitted · v'+c.latest_version:'Awaiting submission'}</strong><p>Due {when(c.due_at)} IST</p><small>Last upload: {c.last_update?when(c.last_update):'Never'}</small></article>)}</div></details>
  <div className="section-heading"><div><h2><History size={18}/>{entity} · Version history</h2></div><input aria-label="Search versions" placeholder="Search files or period…" value={search} onChange={e=>setSearch(e.target.value)}/></div>
  <div className="table-wrap"><table><thead><tr><th>Period / cycle</th><th>Version</th><th>Uploaded · IST</th><th>Files &amp; extraction</th><th>Archive</th></tr></thead><tbody>{records.map(h=><tr key={h.id}><td>{h.period}<small>{h.cadence}</small></td><td>v{h.version}{h.previous_id&&<small>Revises a previous upload</small>}</td><td>{when(h.uploaded_at)}</td><td>{h.files.length} files<small>{h.needs_review?h.needs_review+' documents need review':h.pending_extraction?h.pending_extraction+' pending extraction':'Structured data / supporting files'}</small><details><summary>File list</summary>{h.files.map(f=><small key={f.name}>{f.name} · {f.status.replaceAll('_',' ')}</small>)}</details></td><td><button className="text-button" onClick={()=>void download(h.id)}><Download size={15}/>ZIP</button></td></tr>)}</tbody></table></div>
  {!records.length&&<div className="reference-empty"><FolderArchive size={28}/><h3>{search?'No matching versions':'No submissions yet'}</h3><p>{technical?'Packages appear here when a subsidiary uploads its data.':'Upload your first package to start this report’s version history.'}</p></div>}
  <div className="panel-foot">IST · Provisional deadlines</div></section></div>}
  {!wizard&&error&&<p className="error" role="alert">{error}</p>}
  {wizard&&<dialog ref={dialog} className="upload-wizard" aria-labelledby="upload-title" onCancel={e=>{e.preventDefault();if(!busy)setWizard(false);}}>
   <header><div><h2 id="upload-title">New upload</h2><p>Prepare and submit a report package to CMPDI.</p></div><button className="icon-button" aria-label="Close upload" disabled={busy} onClick={()=>setWizard(false)}><X size={20}/></button></header>
   <ol className="wizard-steps" aria-label="Upload progress">{steps.map((label,index)=><li key={label} className={index===step?'current':index<step?'completed':''} aria-current={index===step?'step':undefined}><span>{index<step?<Check size={16}/>:index+1}</span><strong>{label}</strong></li>)}</ol>
   <div className="wizard-content">
    <h3 ref={focusStep} tabIndex={-1}>{['Choose a report','Choose your ZIP package','Review submission','Submit your package'][step]}</h3>
    {step===0&&<><p>Select the destination, report family and reporting period for this upload.</p>{technical&&<label className="field">Subsidiary<select value={entity} onChange={e=>{const next=e.target.value;setEntity(next);const nextFamilies=schedule?.subsidiaries[next]||{};const nextFamily=Object.keys(nextFamilies)[0]||'production_offtake';setFamily(nextFamily);setCadence(Object.keys(nextFamilies[nextFamily]?.cycles||{})[0]||'daily');}}>{Object.keys(schedule?.subsidiaries||{}).map(x=><option key={x}>{x}</option>)}</select></label>}<label className="field">Report family<select value={family} onChange={e=>{setFamily(e.target.value);setCadence(Object.keys(families[e.target.value].cycles)[0]);}}>{Object.entries(families).map(([k,v])=><option key={k} value={k}>{v.name}</option>)}</select></label><div className="analysis-fields"><label className="field">Reporting cycle<select value={cadence} onChange={e=>setCadence(e.target.value)}>{Object.keys(cycles).map(c=><option key={c}>{c}</option>)}</select></label><label className="field">Reporting period<input required value={period} onChange={e=>setPeriod(e.target.value)} placeholder={format}/><small>{format} · Use an earlier period for a correction.</small></label></div></>}
    {step===1&&<><p>Include one or more files. Nested folders are supported.</p><label className={'zip-dropzone '+(file?'has-file':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();chooseFile(e.dataTransfer.files[0]||null);}}><FileArchive size={34}/><strong>{file?file.name:'Drop your ZIP here'}</strong><span>{file?(file.size/1024**2).toFixed(2)+' MiB · Click to replace':'or click to choose a file'}</span><input aria-label="ZIP package" type="file" accept=".zip,application/zip" onChange={e=>chooseFile(e.target.files?.[0]||null)}/></label><p className="file-guidance">CSV, Excel, JSON, Parquet, PDF or images. Text notes are also accepted.</p><small>Up to 256 MiB ZIP · 500 files · 1 GiB expanded. File validation happens when you submit.</small></>}
    {step===2&&<><p>Check the destination and period before recording a new version.</p><dl className="upload-summary"><dt>Subsidiary</dt><dd>{entity}</dd><dt>Report</dt><dd>{families[family]?.name}</dd><dt>Period</dt><dd>{period} · {cadence}</dd><dt>Package</dt><dd>{file?.name}</dd><dt>Next version</dt><dd>v{(existing?.version||0)+1} (assigned when saved)</dd><dt>Reports to</dt><dd>CMPDI · Technical coordination</dd></dl><label className="confirm-upload"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>This package contains the complete data for this period.{existing?' It replaces the current version for analysis; earlier versions remain in VAULT.':''}</span></label></>}
    {step===3&&<div className="submission-result"><FileCheck2 size={38}/><h3>{complete?'Package stored':busy?'Storing your package…':'Ready to submit'}</h3><p>{complete?notice:'Save this package as a new version.'}</p>{busy&&<div className="upload-progress"><progress value={progress} max={100}/><p>{progress<100?'Uploading '+progress+'%':'Validating files and recording this version…'}</p></div>}</div>}
    {error&&<p className="error" role="alert">{error}</p>}
   </div>
   <footer className="wizard-footer"><button className="button secondary" disabled={busy||complete} onClick={()=>step===0?setWizard(false):setStep(s=>s-1)}>{step===0?'Cancel':'Back'}</button><span>Step {step+1} of 4</span>{complete?<button className="button primary" onClick={()=>setWizard(false)}>Done <Check size={16}/></button>:step===3?<button className="button primary" disabled={busy} onClick={()=>void submit()}><Upload size={16}/>{busy?'Submitting…':'Submit ZIP & create version'}</button>:<button className="button primary" disabled={!schedule||(step===1&&!file)||(step===2&&!confirmed)} onClick={next}>Next <ArrowRight size={16}/></button>}</footer>
  </dialog>}
 </div>;
}
