import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ChevronRight,Download,RefreshCw,Search,SlidersHorizontal,X,FolderOpen,LoaderCircle,MoreVertical,Eye,FileSpreadsheet} from 'lucide-react';

type Entry={name:string;display_name?:string;description?:string;path:string;kind:'file'|'folder';bytes:number|null;modified:number|null};
type ReportOption={id:string;name:string};
type Breadcrumb={path:string;name:string};
type Listing={path:string;breadcrumbs:Breadcrumb[];entries:Entry[];total:number;next_offset:number|null;recursive:boolean;truncated:boolean;filter_options:{entities:string[];reports:Record<string,ReportOption[]>}};
type Preview={entry:Entry;rows:string[][];truncated:boolean;url?:string};
const types=[['all','All items'],['folders','Folders'],['tables','Tables'],['documents','Documents'],['images','Images'],['archives','ZIP archives']];
const periods=[['0','Any time'],['1','Today'],['7','Last 7 days'],['30','Last 30 days'],['366','Last year']];
const sorts=[['name','Name A–Z'],['name_desc','Name Z–A'],['modified','Newest first'],['modified_asc','Oldest first']];
const size=(n:number|null)=>n===null?'':n<1024?n+' B':n<1024**2?(n/1024).toFixed(1)+' KB':n<1024**3?(n/1024**2).toFixed(1)+' MB':(n/1024**3).toFixed(1)+' GB';
const timestamp=(value:number|null)=>value?new Date(value*1000).toLocaleString('en-IN',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'';

function normalizeListing(value:unknown):Listing{
 if(!value||typeof value!=='object'||!Array.isArray((value as {entries?:unknown}).entries))throw Error('The Vault returned an invalid folder response. Refresh after restarting the backend.');
 const raw=value as Partial<Listing>,options=raw.filter_options;
 return {path:typeof raw.path==='string'?raw.path:'',breadcrumbs:Array.isArray(raw.breadcrumbs)?raw.breadcrumbs:[],entries:raw.entries as Entry[],total:typeof raw.total==='number'?raw.total:(raw.entries as Entry[]).length,next_offset:typeof raw.next_offset==='number'?raw.next_offset:null,recursive:Boolean(raw.recursive),truncated:Boolean(raw.truncated),filter_options:{entities:Array.isArray(options?.entities)?options.entities:[],reports:options?.reports&&typeof options.reports==='object'?options.reports:{}}};
}
function FolderIcon(){return <svg className="vault-folder-icon" viewBox="0 0 120 108" aria-hidden="true"><path d="M5 24C5 15.2 12.2 8 21 8h23c4.6 0 9 2.1 12 5.7l6 7.3h42c6.1 0 11 4.9 11 11v55c0 8.8-7.2 16-16 16H21c-8.8 0-16-7.2-16-16V24Z" fill="currentColor"/></svg>}
function FileIcon({name}:{name:string}){const ext=name.split('.').pop()?.toUpperCase()||'FILE';return <svg className="vault-file-icon" viewBox="0 0 100 110" aria-hidden="true"><path d="M18 5H65L84 25V96Q84 104 76 104H18Q10 104 10 96V13Q10 5 18 5Z" fill="var(--file-paper)" stroke="var(--line)"/><path d="M65 5V20Q65 25 70 25H84" fill="var(--surface-alt)" stroke="var(--line)"/><path d="M25 39H68M25 48H68M25 57H58" stroke="#a2adb6" strokeWidth="2.5" strokeLinecap="round"/><rect x="21" y="70" width="52" height="20" rx="3" fill={ext==='PDF'?'#fee4e5':['CSV','XLSX','PARQUET'].includes(ext)?'#dcf3e8':'#e5eefb'}/><text x="47" y="84" textAnchor="middle" fill={ext==='PDF'?'#a82935':['CSV','XLSX','PARQUET'].includes(ext)?'#1b714a':'#375781'} fontSize={ext.length>5?8:10} fontWeight="600" fontFamily="inherit">{ext.slice(0,7)}</text></svg>}

export function VaultWorkspace({token,entityCode,canFilterSubsidiary}:{token:string;entityCode:string;canFilterSubsidiary:boolean}){
 const [history,setHistory]=useState(['']),[index,setIndex]=useState(0),[query,setQuery]=useState(''),[kind,setKind]=useState('all'),[days,setDays]=useState('0'),[sort,setSort]=useState('name'),[entityFilter,setEntityFilter]=useState(''),[reportFilter,setReportFilter]=useState(''),[filters,setFilters]=useState(false),[listing,setListing]=useState<Listing|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<Entry|null>(null),[downloading,setDownloading]=useState(false),[revision,setRevision]=useState(0),[offset,setOffset]=useState(0);
 const [menu,setMenu]=useState<string|null>(null),[preview,setPreview]=useState<Preview|null>(null),[previewLoading,setPreviewLoading]=useState(false),[previewWidth,setPreviewWidth]=useState(38);
 const previewRequest=useRef<AbortController|null>(null),bodyRef=useRef<HTMLDivElement>(null);
 useEffect(()=>()=>previewRequest.current?.abort(),[]);
 useEffect(()=>()=>{if(preview?.url)URL.revokeObjectURL(preview.url)},[preview?.url]);
 function closePreview(){previewRequest.current?.abort();setPreview(null);setPreviewLoading(false)}
 function resizePreview(clientX:number){const rect=bodyRef.current?.getBoundingClientRect();if(rect)setPreviewWidth(Math.min(70,Math.max(25,(rect.right-clientX)/rect.width*100)))}
 const path=history[index],popover=useRef<HTMLDivElement>(null),filterButton=useRef<HTMLButtonElement>(null),grid=useRef<HTMLDivElement>(null),requestNumber=useRef(0);
 const filterCount=Number(Boolean(entityFilter))+Number(Boolean(reportFilter))+Number(kind!=='all')+Number(days!=='0')+Number(sort!=='name'),reportEntity=canFilterSubsidiary?entityFilter:entityCode,reports=reportEntity?(listing?.filter_options?.reports?.[reportEntity]||[]):[];
 useEffect(()=>{const request=++requestNumber.current,controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(async()=>{try{const params=new URLSearchParams({path,q:query,kind,days,sort,offset:String(offset)});if(entityFilter)params.set('entity',entityFilter);if(reportFilter)params.set('report',reportFilter);const r=await fetch('/api/analytics/vault?'+params,{headers:{Authorization:'Bearer '+token},signal:controller.signal}),raw=await r.json();if(!r.ok)throw Error(typeof raw.detail==='string'?raw.detail:'Could not open this folder.');const data=normalizeListing(raw);if(request===requestNumber.current)setListing(previous=>offset&&previous?{...data,entries:[...previous.entries,...data.entries]}:data)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Could not open this folder.')}finally{if(request===requestNumber.current&&!controller.signal.aborted)setLoading(false)}},query?200:0);return()=>{clearTimeout(timer);controller.abort()}},[path,query,kind,days,sort,entityFilter,reportFilter,offset,revision,token]);
 useEffect(()=>{if(!filters)return;const click=(e:PointerEvent)=>{if(!popover.current?.contains(e.target as Node)&&!filterButton.current?.contains(e.target as Node))setFilters(false)},escape=(e:KeyboardEvent)=>{if(e.key==='Escape'){setFilters(false);filterButton.current?.focus()}};document.addEventListener('pointerdown',click);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',click);document.removeEventListener('keydown',escape)}},[filters]);
 function resetView(){setQuery('');setOffset(0);setSelected(null);closePreview();setMenu(null);setListing(null);grid.current?.scrollTo({top:0})}
 function navigate(next:string){resetView();setHistory(old=>[...old.slice(0,index+1),next]);setIndex(index+1)}
 function travel(delta:number){resetView();setIndex(old=>old+delta)}
 function changeFilter(setter:(value:string)=>void,value:string){setter(value);setOffset(0);setSelected(null)}
 function resetToRoot(){setHistory(['']);setIndex(0);setOffset(0);setSelected(null);setPreview(null);setListing(null)}
 function changeEntity(value:string){setEntityFilter(value);setReportFilter('');resetToRoot()}
 function changeReport(value:string){setReportFilter(value);resetToRoot()}
 function resetFilters(){setEntityFilter('');setReportFilter('');setKind('all');setDays('0');setSort('name');setOffset(0);setSelected(null)}
 async function download(entry:Entry){if(downloading)return;setDownloading(true);setError('');try{const r=await fetch('/api/analytics/vault/file?'+new URLSearchParams({path:entry.path}),{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('File unavailable. Refresh the folder and try again.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=entry.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}catch(e){setError(e instanceof Error?e.message:'Download failed.')}finally{setDownloading(false)}}
 async function openPreview(entry:Entry){
  previewRequest.current?.abort();const controller=new AbortController();previewRequest.current=controller;
  setSelected(entry);setMenu(null);setPreview({entry,rows:[],truncated:false});setPreviewLoading(true);setError('');
  try{
   const pdf=entry.name.toLowerCase().endsWith('.pdf'),csv=entry.name.toLowerCase().endsWith('.csv');
   if(!pdf&&!csv)return;
   const r=await fetch('/api/analytics/vault/'+(pdf?'file':'preview')+'?'+new URLSearchParams({path:entry.path}),{headers:{Authorization:'Bearer '+token},signal:controller.signal});
   if(!r.ok)throw Error('Preview unavailable. Refresh the folder and try again.');
   if(pdf){const blob=await r.blob();if(!controller.signal.aborted)setPreview({entry,rows:[],truncated:false,url:URL.createObjectURL(new Blob([blob],{type:'application/pdf'}))})}
   else {const data=await r.json();if(!controller.signal.aborted)setPreview({entry,rows:data.rows,truncated:data.truncated})}
  }catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Preview failed.')}
  finally{if(!controller.signal.aborted)setPreviewLoading(false)}
 }
 const crumbs=listing?.breadcrumbs||path.split('/').filter(Boolean).map((name,index,all)=>({name,path:all.slice(0,index+1).join('/')})),entries=listing?.entries||[];
 return <section className="vault-explorer" aria-label="Vault file explorer">
  <div className="vault-toolbar"><div className="vault-navigation"><button className="icon-button" aria-label="Back" disabled={index===0} onClick={()=>travel(-1)}><ArrowLeft size={18}/></button><button className="icon-button" aria-label="Forward" disabled={index===history.length-1} onClick={()=>travel(1)}><ArrowRight size={18}/></button><nav className="vault-breadcrumbs" aria-label="Folder path"><FolderOpen size={17}/><button onClick={()=>navigate('')} aria-current={!path?'page':undefined}>Data/cil</button>{crumbs.map((part,i)=><span key={part.path}><ChevronRight size={14}/><button aria-current={i===crumbs.length-1?'page':undefined} title={part.name} onClick={()=>navigate(part.path)}>{part.name}</button></span>)}</nav></div>
   <div className="vault-tools"><label className="vault-search"><Search size={17}/><input aria-label="Search vault" placeholder="Search vault" value={query} onChange={e=>changeFilter(setQuery,e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>changeFilter(setQuery,'')}><X size={14}/></button>}</label><div className="vault-filter-anchor"><button ref={filterButton} className={'button secondary vault-filter-button '+(filterCount?'is-filtered':'')} aria-expanded={filters} aria-controls="vault-filters" onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/>Filter{filterCount>0&&<span>{filterCount}</span>}</button>{filters&&<div ref={popover} id="vault-filters" className="vault-filter-menu">
    {canFilterSubsidiary&&<label className="field">Subsidiary<select aria-label="Subsidiary" value={entityFilter} onChange={e=>changeEntity(e.target.value)}><option value="">All subsidiaries</option>{listing?.filter_options?.entities?.map(entity=><option key={entity} value={entity}>{entity}</option>)}</select></label>}<label className="field">Report<select aria-label="Report" value={reportFilter} disabled={!reportEntity} onChange={e=>changeReport(e.target.value)}><option value="">{reportEntity?'All reports':'Choose a subsidiary first'}</option>{reports.map(report=><option key={report.id} value={report.id}>{report.name}</option>)}</select></label><label className="field">Type<select aria-label="File type" value={kind} onChange={e=>changeFilter(setKind,e.target.value)}>{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field">Updated<select aria-label="Updated" value={days} onChange={e=>changeFilter(setDays,e.target.value)}>{periods.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field">Sort by<select aria-label="Sort by" value={sort} onChange={e=>changeFilter(setSort,e.target.value)}>{sorts.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div><button className="text-button" onClick={resetFilters}>Reset</button><button className="button primary" onClick={()=>{setFilters(false);filterButton.current?.focus()}}>Done</button></div></div>}</div><button className="icon-button" aria-label="Refresh folder" disabled={loading} onClick={()=>{setOffset(0);setRevision(v=>v+1)}}><RefreshCw size={17} className={loading?'spin':''}/></button></div>
  </div>
  {filterCount>0&&<div className="vault-filter-chips">{entityFilter&&<button onClick={()=>changeEntity('')}>{entityFilter}<X size={12}/></button>}{reportFilter&&<button onClick={()=>changeReport('')}>{reports.find(item=>item.id===reportFilter)?.name||reportFilter}<X size={12}/></button>}{kind!=='all'&&<button onClick={()=>changeFilter(setKind,'all')}>{types.find(item=>item[0]===kind)?.[1]}<X size={12}/></button>}{days!=='0'&&<button onClick={()=>changeFilter(setDays,'0')}>{periods.find(item=>item[0]===days)?.[1]}<X size={12}/></button>}{sort!=='name'&&<button onClick={()=>changeFilter(setSort,'name')}>{sorts.find(item=>item[0]===sort)?.[1]}<X size={12}/></button>}</div>}
  {error&&<div className="error" role="alert">{error}<button className="text-button" onClick={()=>setError('')}>Dismiss</button></div>}
  <div ref={bodyRef} style={preview?{gridTemplateColumns:`minmax(0,1fr) 8px minmax(0,${previewWidth}%)`}:undefined} className={'vault-body '+(preview||previewLoading?'has-preview':'')}><div className="vault-grid" ref={grid} aria-busy={loading} aria-label="Folders and files">
   {(!loading||offset>0)&&!error&&entries.map(entry=><article key={entry.path} className={'vault-item '+(selected?.path===entry.path?'selected':'')}>
    <button className="vault-item-main" title={entry.description||entry.display_name||entry.name} aria-label={(entry.kind==='folder'?'Open folder ':'Preview file ')+(entry.display_name||entry.name)} onClick={()=>entry.kind==='folder'?navigate(entry.path):void openPreview(entry)}>{entry.kind==='folder'?<FolderIcon/>:<FileIcon name={entry.name}/>}<span>{entry.display_name||entry.name}</span>{entry.description&&<small>{entry.description}</small>}{!entry.description&&listing?.recursive&&<small>{entry.path.split('/').slice(0,-1).join('/')||'Data/cil'}</small>}{entry.kind==='file'&&entry.modified&&<time dateTime={new Date(entry.modified*1000).toISOString()}>{timestamp(entry.modified)}</time>}</button>
    {entry.kind==='file'&&<><button className="vault-item-menu-button" aria-label={`Actions for ${entry.name}`} aria-expanded={menu===entry.path} onClick={()=>{setSelected(entry);setMenu(menu===entry.path?null:entry.path)}}><MoreVertical size={17}/></button>{menu===entry.path&&<div className="vault-item-menu"><button onClick={()=>void openPreview(entry)}><Eye size={15}/>Open preview</button></div>}</>}</article>)}
   {loading&&!offset&&<div className="vault-empty" role="status"><LoaderCircle className="spin" size={24}/><span>Loading…</span></div>}{!loading&&!error&&!entries.length&&<div className="vault-empty"><FolderOpen size={30}/><span>{query||filterCount?'No matches':'Empty folder'}</span>{Boolean(query||filterCount)&&<button className="text-button" onClick={()=>{setQuery('');resetFilters()}}>Clear filters</button>}</div>}
  </div>{(preview||previewLoading)&&<><div className="vault-preview-resizer" role="separator" aria-label="Resize preview" aria-orientation="vertical" aria-valuenow={Math.round(previewWidth)} aria-valuemin={25} aria-valuemax={70} tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();setPreviewWidth(w=>Math.max(25,Math.min(70,w+(e.key==='ArrowLeft'?2:-2))))}}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);resizePreview(e.clientX)}} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))resizePreview(e.clientX)}} onPointerUp={e=>e.currentTarget.releasePointerCapture(e.pointerId)}/><aside className="vault-preview" aria-label="File preview">{previewLoading?<div className="vault-preview-loading"><LoaderCircle className="spin"/><span>Preparing preview…</span></div>:preview&&<><header><div><FileSpreadsheet size={18}/><span><strong>{preview.entry.name}</strong><small>{preview.entry.bytes===null?'':size(preview.entry.bytes)}</small></span></div><button className="icon-button" aria-label="Close preview" onClick={closePreview}><X size={17}/></button></header>{preview.url?<iframe className="vault-pdf" title={`PDF preview: ${preview.entry.name}`} src={preview.url}/>:preview.rows.length?<div className="vault-dataframe"><table><thead><tr><th>#</th>{(preview.rows[0]||[]).map((cell,i)=><th key={i} title={cell}>{cell||`Column ${i+1}`}</th>)}</tr></thead><tbody>{preview.rows.slice(1).map((row,i)=><tr key={i}><th>{i+1}</th>{(preview.rows[0]||[]).map((_,k)=><td key={k} title={row[k]||''}>{row[k]||''}</td>)}</tr>)}</tbody></table></div>:<div className="vault-preview-loading">No inline preview available. Download to open this file.</div>}{preview.truncated&&<p>Showing the first 100 rows. Download the file for the complete dataset.</p>}<footer><button className="button secondary" onClick={()=>void download(preview.entry)}><Download size={15}/>Download</button></footer></>}</aside></>}</div>
  <footer className="vault-status"><span aria-live="polite">{selected?selected.name:listing?listing.total+' '+(listing.recursive?'results':'items'):''}{selected?.bytes!==null&&selected&&<small> · {size(selected.bytes)}</small>}{selected?.modified&&<small> · {timestamp(selected.modified)}</small>}</span>{selected?.kind==='file'&&!preview&&<button className="text-button" disabled={downloading} onClick={()=>void download(selected)}>{downloading?<LoaderCircle size={15} className="spin"/>:<Download size={15}/>}Download</button>}{listing?.next_offset!==null&&listing?.next_offset!==undefined&&<button className="text-button" disabled={loading} onClick={()=>setOffset(listing.next_offset!)}>Load more</button>}</footer>{listing?.truncated&&<p className="vault-limit">Search limited. Open a folder to narrow results.</p>}
 </section>
}
