import {useEffect,useRef,useState,type ReactNode} from 'react';
import {MessageSquare,LayoutDashboard,CalendarCheck,Search,ClipboardCheck,FilePenLine,Settings,User,LogOut,Sun,Moon,Menu,Building2,Users,Shield,Palette,ChevronDown,X,KeyRound} from 'lucide-react';
import type {Identity} from './types';
export type ToolView='inputs'|'vault'|'analysis'|'extraction'|'reports';
export type SettingsSection='overview'|'profile'|'security'|'appearance'|'models';
const tools=[{id:'inputs',label:'UPLOAD',icon:LayoutDashboard},{id:'vault',label:'VAULT',icon:CalendarCheck},{id:'analysis',label:'ALALYSE',icon:Search},{id:'extraction',label:'AUDIT',icon:ClipboardCheck},{id:'reports',label:'DRAFT',icon:FilePenLine}] as const;
export function WorkspaceBrand(){return <div className="workspace-brand"><span><MessageSquare size={21}/></span><strong>CIL MAGMENT SOFTWARE</strong></div>;}
export function WorkspaceSidebar({identity,page,view,onPage,onTool,onProfile,onSignout,mobile,onClose}:{identity:Identity;page:string;view:ToolView;onPage:(page:string)=>void;onTool:(view:ToolView)=>void;onProfile:()=>void;onSignout:()=>void;mobile:boolean;onClose:()=>void}){
 const [menu,setMenu]=useState(false);const account=useRef<HTMLDivElement>(null);const admin=identity.profile.role==='cil_admin';
 const name=identity.profile.role==='cmpdi'?'CMPDIL ADMIN':identity.profile.full_name;
 useEffect(()=>{if(!menu)return;const close=(e:PointerEvent)=>{if(!account.current?.contains(e.target as Node))setMenu(false);};const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);};document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);};},[menu]);
 const navigate=(id:string)=>{onPage(id);setMenu(false);onClose();};
 return <><aside className={'sidebar reference-sidebar '+(mobile?'open':'')} aria-label="Workspace navigation"><WorkspaceBrand/><button className="icon-button sidebar-close mobile-only" aria-label="Close navigation" onClick={onClose}><X size={18}/></button>
  <nav aria-label="Main navigation">{admin?[{id:'overview',label:'Dashboard',icon:LayoutDashboard},{id:'vault',label:'Vault',icon:CalendarCheck},{id:'entities',label:'Entity master',icon:Building2},{id:'people',label:'Access & people',icon:Users}].map(n=><button key={n.id} className={page===n.id?'active':''} aria-current={page===n.id?'page':undefined} onClick={()=>navigate(n.id)}><n.icon size={19}/>{n.label}</button>):tools.map(n=><button key={n.id} className={page==='analytics'&&view===n.id?'active':''} aria-current={page==='analytics'&&view===n.id?'page':undefined} onClick={()=>{onTool(n.id);onClose();}}><n.icon size={19}/>{n.label}</button>)}</nav>
  <div className="sidebar-utility">{!admin&&<button className={page==='overview'?'active':''} aria-current={page==='overview'?'page':undefined} onClick={()=>navigate('overview')}><Building2 size={19}/>Workspace overview</button>}<button className={page==='security'?'active':''} aria-current={page==='security'?'page':undefined} onClick={()=>navigate('security')}><Settings size={19}/>Settings</button></div>
  <div className="sidebar-bottom" ref={account}>{menu&&<div id="account-menu" className="profile-popover" role="menu" aria-label="Account options"><button role="menuitem" onClick={()=>{onProfile();setMenu(false);onClose();}}><User size={18}/>Profile</button><button role="menuitem" onClick={()=>navigate('security')}><Settings size={18}/>Settings</button><button role="menuitem" onClick={()=>{setMenu(false);onSignout();}}><LogOut size={18}/>Sign out</button></div>}<button className="user-block" aria-expanded={menu} aria-controls="account-menu" aria-haspopup="menu" aria-label="Open account menu" onClick={()=>setMenu(!menu)}><span className="avatar">{identity.profile.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span><strong>{name}</strong><small>{identity.entity.code} · {admin?'Central administration':identity.profile.role==='cmpdi'?'Technical coordination':'Reports to CMPDI'}</small></span><ChevronDown size={14}/></button></div>
 </aside>{mobile&&<button className="mobile-scrim" aria-label="Close navigation overlay" onClick={onClose}/>}</>;
}
export function WorkspaceHeader({title,identity,dark,onTheme,onMenu,onProfile,action}:{title:string;identity:Identity;dark:boolean;onTheme:()=>void;onMenu:()=>void;onProfile:()=>void;action?:ReactNode}){
 return <header className="topbar reference-topbar"><div className="topbar-title"><button className="icon-button mobile-only" aria-label="Open navigation" onClick={onMenu}><Menu size={20}/></button><h1>{title}</h1></div><div className="topbar-actions">{action&&<div className="header-action">{action}</div>}<button className="icon-button" aria-label={dark?'Switch to light mode':'Switch to dark mode'} onClick={onTheme}>{dark?<Moon size={21}/>:<Sun size={21}/>}</button><button className="header-profile" onClick={onProfile} aria-label={`Open profile for ${identity.profile.full_name}`}><span className="avatar">{identity.profile.full_name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span>{identity.profile.role==='cmpdi'?'CMPDIL ADMIN':identity.profile.full_name}</span></button></div></header>;
}
export function SettingsLayout({section,onSection,admin,canManageModels,onEntities,onPeople,children}:{section:SettingsSection;onSection:(section:SettingsSection)=>void;admin:boolean;canManageModels:boolean;onEntities:()=>void;onPeople:()=>void;children:ReactNode}){
 return <div className="settings-layout" data-section={section}><nav aria-label="Settings sections"><button className={section==='overview'?'active':''} aria-current={section==='overview'?'page':undefined} onClick={()=>onSection('overview')}><LayoutDashboard size={18}/>Overview</button><span>ACCOUNT</span>{([{id:'profile',label:'Your profile',icon:User},{id:'security',label:'Login & security',icon:Shield},{id:'appearance',label:'Appearance',icon:Palette}] as const).map(n=><button key={n.id} className={section===n.id?'active':''} aria-current={section===n.id?'page':undefined} onClick={()=>onSection(n.id)}><n.icon size={18}/>{n.label}</button>)}<span>WORKSPACE</span>{canManageModels&&<button className={section==='models'?'active':''} aria-current={section==='models'?'page':undefined} onClick={()=>onSection('models')}><KeyRound size={18}/>AI providers</button>}<button onClick={onEntities}><Building2 size={18}/>{admin?'Entity master':'Subsidiaries'}</button>{admin&&<button onClick={onPeople}><Users size={18}/>Team members</button>}</nav><div className="settings-content">{children}</div></div>;
}
